language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  # Install Codecov
  - pip install codecov

  # Install requirements
  - pip install -r requirements.txt

script:
  # Do essentially nothing (yet)
  - coverage run run_yaft.py

after_success:
  # Upload code coverage to Codecov
  - codecov
