language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

services:
  - postgresql

install:
  # Set up PostgreSQL database
  - psql --command "CREATE DATABASE yaft;"
  - psql --command "CREATE USER azurediamond WITH PASSWORD 'hunter1';"
  - psql --command "GRANT ALL PRIVILEGES ON DATABASE yaft TO azurediamond;"

  # Install Codecov
  - pip install codecov

  # Install requirements
  - pip install -r requirements.txt

  # Set up config file
  - cp config.yaml.example config.yaml

script:
  # Do essentially nothing (yet)
  - coverage run run_yaft.py

after_success:
  # Upload code coverage to Codecov
  - codecov
